export const selectors = {
  authenticatedMarkers: [
    "a[href*='logout']",
    "a:has-text('Đăng xuất')",
    "text=Tra cứu lịch",
    "a[href*='lichhoc']",
  ],
  scheduleRegions: [
    "#datebody",
    ".aps-lichhoc",
    "#lichhoc",
    "[id*='lichhoc' i]",
    "[class*='schedule' i]",
    "[class*='calendar' i]",
    ".fc-view-container",
    ".fc-view",
  ],
  eventCards: [
    "#datebody .task.btnLichHoc",
    "#datebody .task.btnLichThi",
    "#datebody .task",
    "[data-event]",
    "[data-date][class*='event' i]",
    ".fc-event",
    "[class*='event-item' i]",
    "[class*='schedule-item' i]",
    "[class*='lichhoc' i] [class*='item' i]",
  ],
  weekLabels: [
    ".my-calendar [batdau][ketthuc].active",
    "#date-header",
    "[class*='week' i] [class*='title' i]",
    "[class*='calendar' i] [class*='title' i]",
    ".fc-toolbar-title",
    "h2:has-text('/')",
    "h3:has-text('/')",
  ],
  nextWeek: [
    "button[aria-label*='next' i]",
    "button[title*='tiếp' i]",
    "a[title*='tiếp' i]",
    ".fc-next-button",
    "button:has-text('Tuần sau')",
    "a:has-text('Tuần sau')",
    "button:has-text('Sau')",
  ],
  previousWeek: [
    "button[aria-label*='prev' i]",
    "button[title*='trước' i]",
    "a[title*='trước' i]",
    ".fc-prev-button",
    "button:has-text('Tuần trước')",
    "a:has-text('Tuần trước')",
  ],
  examMenu: [
    "a:has-text('Lịch thi')",
    "[role='menuitem']:has-text('Lịch thi')",
    "a[href*='lichthi' i]",
    "a[href*='exam' i]",
  ],
  withoutDetailRegions: [
    "#zoneTKBKhongLichChiTiet",
    "text=Lớp học phần (không có lịch chi tiết)",
    "[class*='no-schedule' i]",
  ],
} as const;
